---
- hosts: gateway.tdmu.local
  sudo: yes
  vars:
#  - hostname: test123
#  - serverip: 99
  tasks:
  - name: add to zones
    lineinfile: dest=/etc/bind/zones/db.tdmu.local  line="{{hostname}}		IN      A       10.1.1.{{serverip}}" state=present
  - name: add to reverse zones
    lineinfile: dest=/etc/bind/zones/db.10  line="{{serverip}}	IN      PTR     {{hostname}}.tdmu.local." state=present
  - name: restart dns
    service: name=bind9 state=restarted

#- hosts: 10.1.1.{{serverip}}
#  sudo: yes
#  tasks:
#  - name: add hostname to /etc/hostname 
#    hostname: name={{hostname}}.tdmu.local
#  - name: add /etc/hosts
#    lineinfile: dest=/etc/hosts  line="10.1.1.{{serverip}}      {{hostname}}.tdmu.local       {{hostname}}" state=present
